### ISSUE TITLE
详细的过程有么？

### ISSUE THREAD

**Issue by dev-du** [windshadow233/ws-tls-nginx#1]
用什么客户端？

**Comment by windshadow233** [comment]
客户端看具体操作系统，例如Windows系统可用v2rayN，ios用shadowrocket等。
另外，详细的过程是指？

**Comment by dev-du** [comment]
感谢回复！
我再试试，用的是macos；
没准备好域名，所以还没有部署成功，域名在哪个平台注册比较好哈？

**Comment by windshadow233** [comment]
> 

Mac OS好像多用clashX，域名随便找一个国内的域名商都行，我之前用的是阿里云的。服务器得用境外的。

**Comment by dev-du** [comment]
好的 感谢

**Comment by dev-du** [comment]
搭建完成试了clashX发现不会配啊 --！

**Comment by windshadow233** [comment]
> 搭建完成试了clashX发现不会配啊 --！

clash是根据规则文件来工作的，vmess或vless链接并不能直接导入，你可以上网了解一下单节点链接转clash配置文件的方法，这里有一个repo可以参考一下：[](https://github.com/CareyWang/sub-web)

**Comment by windshadow233** [comment]
> 搭建完成试了clashX发现不会配啊 --！

clash是根据规则文件来工作的，vmess或vless链接并不能直接导入，你可以上网了解一下单节点链接转clash配置文件的方法，这里有一个repo可以参考一下：[[CareyWang/sub-web](https://github.com/CareyWang/sub-web)](https://github.com/CareyWang/sub-web)

**Comment by windshadow233** [comment]
> 搭建完成试了clashX发现不会配啊 --！

clash是根据规则文件来工作的，vmess或vless链接并不能直接导入，你可以上网了解一下单节点链接转clash配置文件的方法，这里有一个repo可以参考一下：[sub-web](https://github.com/CareyWang/sub-web)

**Comment by windshadow233** [comment]
> 搭建完成试了clashX发现不会配啊 --！

clash是根据规则文件来工作的，vmess或vless链接并不能直接导入，你可以上网了解一下单节点链接转clash配置文件的方法，这里有一个repo可以参考一下：[subconverter](https://github.com/tindy2013/subconverter)

**Comment by dev-du** [comment]
改用了v2rayU，可以进入谷歌香港官网，但是搜索会被拦截，有遇到过么？

**Comment by windshadow233** [comment]
> 改用了v2rayU，可以进入谷歌香港官网，但是搜索会被拦截，有遇到过么？

这个大概是节点ip的问题

**Comment by dev-du** [comment]
好的 谢了哈

**Comment by windshadow233** [comment]
> 好的 谢了哈

没事，有问题可以加个tg讨论～

**Comment by dev-du** [comment]
森么是tg啊？
